spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javatechie
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ENC(2kE0igaFJz+PwTmAMErhcX4flCjqJopfIbaAbiOf2kkN7autVRe0A72WwhoCukuU)
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080


